upstream_project_url: https://github.com/nikromen/mockpod
specfile_path: files/mockpod.spec
downstream_package_name: mockpod
upstream_package_name: mockpod

srpm_build_deps:
  - python3-hatchling

actions:
  create-archive:
    - python3 -m hatchling build -t sdist
    - bash -c "ls dist/mockpod-*.tar.gz"
  get-current-version:
    - python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    tmt_plan: /plans/integration
    tf_extra_params:
      environments:
        - settings:
            provisioning:
              tags:
                - BaseOS

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    owner: "nikromen"
    project: "mockpod"
    branch: main
    list_on_homepage: True
    preserve_project: True
    actions:
      post-modifications:
        - bash -c "sed -i '1i%global git_build 1' files/mockpod.spec"

  - job: copr_build
    trigger: release
    targets:
      - fedora-all
    owner: "nikromen"
    project: "mockpod"
    list_on_homepage: True
    preserve_project: True
